name: CI
on:
  pull_request:
    branches:
      - production

jobs:
  create-gmud:
    runs-on: ubuntu-latest
    name: 'create-gmud'
    steps:
      - uses: madeiramadeirabr/action-generate-gmud-sre@v1
        with: 
          domain: 'madeiramadeira'
          basic-auth: ${{ secrets.GLOBALS_SRE_BASIC_AUTH_JIRA }}
          api-key: ${{ secrets.GLOBALS_SRE_APIKEY_JAZZ_GMUD }}
          auth-github: ${{ secrets.GLOBALS_SRE_BASIC_AUTH_GITHUB }}
          service-desk-id: '31'
          request-type-id: '538'
          technical-approval: ${{ secrets.TECHNICAL_APPROVAL }}
          business-approval: ${{ secrets.BUSINESS_APPROVAL }}
          url-pull-request: ${{ github.event.pull_request._links.self.href }}/${{ github.run_id}}
          url-slifer-gmud: ${{ secrets.GLOBALS_SRE_URL_SLIFER_GMUD }}
             
      - uses: madeiramadeirabr/action-validate-deploy-date@production
        with:
          domain: "madeiramadeira"
          basic-auth: ${{ secrets.BASIC_AUTH_JIRA }}
